name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name mongodb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint
      
      - name: Set DB_URL environment variable
        run: echo "DB_URL=mongodb://localhost:27017/pindie" >> $GITHUB_ENV
      
      - name: Start MongoDB
        run: sleep 10s
      
      - name: Create pindie database
        run: mongo --eval "db.getSiblingDB('pindie')"

      - name: 'Test server'
        uses: miguelteixeiraa/action-run-in-background@v1
        with:
          script: |
            npm start

          readiness-script: |
            # check if whatever is it to run, is ready
            if curl -sSf http://localhost:3000/api/ping > /dev/null; then
                echo "curl request was successful."
            else
                echo "curl request failed."
                exit 1
            fi

          shell: bash
          timeout: 30
